#!/usr/bin/env python3
# Writes HomeScreen.kt cleanly
import os

target = os.path.join(
    r"c:\Users\yosef dahan\Documents\GitHub\sterni\android\app\src\main\java",
    "com", "sterni", "dailystudy", "ui", "screens", "home", "HomeScreen.kt"
)

lines = []
def L(s=""):
    lines.append(s)

L("package com.sterni.dailystudy.ui.screens.home")
L()
L("import androidx.compose.animation.AnimatedVisibility")
L("import androidx.compose.animation.core.tween")
L("import androidx.compose.animation.fadeIn")
L("import androidx.compose.animation.slideInVertically")
L("import androidx.compose.foundation.Canvas")
L("import androidx.compose.foundation.background")
L("import androidx.compose.foundation.clickable")
L("import androidx.compose.foundation.layout.*")
L("import androidx.compose.foundation.lazy.LazyColumn")
L("import androidx.compose.foundation.lazy.itemsIndexed")
L("import androidx.compose.foundation.shape.CircleShape")
L("import androidx.compose.foundation.shape.RoundedCornerShape")
L("import androidx.compose.material.icons.Icons")
L("import androidx.compose.material.icons.automirrored.filled.MenuBook")
L("import androidx.compose.material.icons.filled.AccessTime")
L("import androidx.compose.material.icons.filled.Build")
L("import androidx.compose.material.icons.filled.CalendarMonth")
L("import androidx.compose.material.icons.filled.DateRange")
L("import androidx.compose.material.icons.filled.Home")
L("import androidx.compose.material.icons.rounded.Refresh")
L("import androidx.compose.material.icons.rounded.Settings")
L("import androidx.compose.material3.*")
L("import androidx.compose.runtime.*")
L("import androidx.compose.ui.Alignment")
L("import androidx.compose.ui.Modifier")
L("import androidx.compose.ui.draw.clip")
L("import androidx.compose.ui.graphics.Brush")
L("import androidx.compose.ui.graphics.Color")
L("import androidx.compose.ui.graphics.StrokeCap")
L("import androidx.compose.ui.graphics.drawscope.Stroke")
L("import androidx.compose.ui.graphics.vector.ImageVector")
L("import androidx.compose.ui.platform.LocalContext")
L("import androidx.compose.ui.text.font.FontWeight")
L("import androidx.compose.ui.text.style.TextAlign")
L("import androidx.compose.ui.text.style.TextDirection")
L("import androidx.compose.ui.text.style.TextOverflow")
L("import androidx.compose.ui.unit.dp")
L("import androidx.compose.ui.unit.sp")
L("import androidx.hilt.navigation.compose.hiltViewModel")
L("import androidx.lifecycle.compose.collectAsStateWithLifecycle")
L("import com.sterni.dailystudy.data.model.Study")
L("import com.sterni.dailystudy.tracker.StudyTracker")
L("import com.sterni.dailystudy.ui.theme.BaHaYetzira")
L("import com.sterni.dailystudy.ui.theme.SblHebrew")
L()
L("@OptIn(ExperimentalMaterial3Api::class)")
L("@Composable")
L("fun HomeScreen(")
L('    onStudyClick: (studyKey: String, date: String, title: String, label: String) -> Unit,')
L("    onZmanimClick:   () -> Unit = {},")
L("    onMamaarimClick: () -> Unit = {},")
L("    onLocationClick: () -> Unit = {},")
L("    onTrackerClick:  () -> Unit = {},")
L("    onCalendarClick: () -> Unit = {},")
L("    onSettingsClick: () -> Unit = {},")
L("    onToolsClick:    () -> Unit = {},")
L("    onTefilaClick:   () -> Unit = {},")
L("    onOmerClick:     () -> Unit = {},")
L("    viewModel: HomeViewModel = hiltViewModel()")
L(") {")
L("    val uiState by viewModel.uiState.collectAsStateWithLifecycle()")
L("    val context = LocalContext.current")
L("    var todayStatus by remember { mutableStateOf(StudyTracker.getTodayStatus(context)) }")
L()
L("    Scaffold(")
L("        bottomBar = {")
L("            NavigationBar(")
L("                containerColor = MaterialTheme.colorScheme.surface,")
L("                tonalElevation = 8.dp")
L("            ) {")
L("                NavigationBarItem(")
L("                    selected = true,")
L("                    onClick = {},")
L("                    icon = { Icon(Icons.Default.Home, contentDescription = null) },")
L('                    label = { Text("\u05d1\u05d9\u05ea", fontWeight = FontWeight.Bold) },')
L("                    colors = NavigationBarItemDefaults.colors(")
L("                        selectedIconColor = MaterialTheme.colorScheme.primary,")
L("                        selectedTextColor = MaterialTheme.colorScheme.primary,")
L("                        indicatorColor = MaterialTheme.colorScheme.primaryContainer")
L("                    )")
L("                )")
L("                NavigationBarItem(")
L("                    selected = false,")
L("                    onClick = onZmanimClick,")
L("                    icon = { Icon(Icons.Default.AccessTime, contentDescription = null) },")
L('                    label = { Text("\u05d6\u05de\u05e0\u05d9\u05dd") },')
L("                    colors = NavigationBarItemDefaults.colors(")
L("                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,")
L("                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant")
L("                    )")
L("                )")
L("                NavigationBarItem(")
L("                    selected = false,")
L("                    onClick = onToolsClick,")
L("                    icon = { Icon(Icons.Default.Build, contentDescription = null) },")
L('                    label = { Text("\u05db\u05dc\u05d9\u05dd") },')
L("                    colors = NavigationBarItemDefaults.colors(")
L("                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,")
L("                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant")
L("                    )")
L("                )")
L("                NavigationBarItem(")
L("                    selected = false,")
L("                    onClick = onCalendarClick,")
L("                    icon = { Icon(Icons.Default.CalendarMonth, contentDescription = null) },")
L('                    label = { Text("\u05dc\u05d5\u05d7") },')
L("                    colors = NavigationBarItemDefaults.colors(")
L("                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,")
L("                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant")
L("                    )")
L("                )")
L("            }")
L("        },")
L("        containerColor = MaterialTheme.colorScheme.background")
L("    ) { paddingValues ->")
L("        Box(modifier = Modifier.fillMaxSize().padding(paddingValues)) {")
L("            when {")
L("                uiState.isLoading -> CircularProgressIndicator(")
L("                    modifier = Modifier.align(Alignment.Center),")
L("                    color = MaterialTheme.colorScheme.primary")
L("                )")
L("                uiState.error != null -> ErrorState(")
L("                    message = uiState.error!!,")
L("                    onRetry = { viewModel.loadDailyStudy() },")
L("                    modifier = Modifier.align(Alignment.Center)")
L("                )")
L("                else -> {")
L('                    val orderedKeys = listOf("chumash", "rambam", "rambamOne", "tanya", "seferHamitzvot", "shnayimMikra", "tehillim")')
L("                    val orderedStudies = orderedKeys.mapNotNull { key -> uiState.studies[key]?.let { key to it } }")
L("                    LazyColumn(contentPadding = PaddingValues(bottom = 32.dp), modifier = Modifier.fillMaxSize()) {")
L("                        item {")
L("                            HomeHeroSection(")
L("                                hebrewDate = uiState.hebrewDate,")
L("                                onSettingsClick = onSettingsClick,")
L("                                onRefreshClick = {")
L("                                    viewModel.loadDailyStudy()")
L("                                    todayStatus = StudyTracker.getTodayStatus(context)")
L("                                }")
L("                            )")
L("                        }")
L("                        if (todayStatus.isNotEmpty()) {")
L("                            item {")
L("                                DailyProgressCard(todayStatus = todayStatus)")
L("                                Spacer(modifier = Modifier.height(8.dp))")
L("                            }")
L("                        }")
L("                        item {")
L("                            QuickAccessRow(onTefilaClick = onTefilaClick, onOmerClick = onOmerClick, onToolsClick = onToolsClick)")
L("                            Spacer(modifier = Modifier.height(8.dp))")
L("                        }")
L("                        itemsIndexed(orderedStudies, key = { _, pair -> pair.first }) { index, (key, study) ->")
L("                            AnimatedVisibility(")
L("                                visible = true,")
L("                                enter = slideInVertically(initialOffsetY = { 50 + (index * 20) }, animationSpec = tween(400)) + fadeIn(animationSpec = tween(400))")
L("                            ) {")
L("                                StudyCard(")
L("                                    study = study,")
L("                                    modifier = Modifier.padding(horizontal = 16.dp).padding(vertical = 8.dp),")
L("                                    onClick = {")
L("                                        if (study.available == true) {")
L('                                            onStudyClick(key, uiState.date, study.title ?: "", study.label ?: "")')
L("                                        }")
L("                                    }")
L("                                )")
L("                            }")
L("                        }")
L("                    }")
L("                }")
L("            }")
L("        }")
L("    }")
L("}")
L()
L("@Composable")
L("fun HomeHeroSection(")
L("    hebrewDate: String,")
L("    onSettingsClick: () -> Unit,")
L("    onRefreshClick: () -> Unit")
L(") {")
L("    Box(")
L("        modifier = Modifier")
L("            .fillMaxWidth()")
L("            .clip(RoundedCornerShape(bottomStart = 32.dp, bottomEnd = 32.dp))")
L("            .background(Brush.verticalGradient(colors = listOf(MaterialTheme.colorScheme.primary, MaterialTheme.colorScheme.primary.copy(alpha = 0.85f))))")
L("            .padding(bottom = 24.dp)")
L("    ) {")
L("        Column {")
L("            Spacer(Modifier.statusBarsPadding())")
L("            Row(")
L("                modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 16.dp),")
L("                horizontalArrangement = Arrangement.SpaceBetween,")
L("                verticalAlignment = Alignment.Top")
L("            ) {")
L("                Column(modifier = Modifier.weight(1f)) {")
L("                    Text(")
L('                        text = "\u05dc\u05d9\u05de\u05d5\u05d3 \u05d9\u05d5\u05de\u05d9",')
L("                        fontSize = 34.sp,")
L("                        fontWeight = FontWeight.ExtraBold,")
L("                        color = MaterialTheme.colorScheme.onPrimary,")
L("                        fontFamily = BaHaYetzira")
L("                    )")
L("                    Spacer(Modifier.height(4.dp))")
L("                    if (hebrewDate.isNotEmpty()) {")
L("                        Surface(")
L("                            shape = RoundedCornerShape(12.dp),")
L("                            color = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.2f)")
L("                        ) {")
L("                            Text(")
L("                                text = hebrewDate,")
L("                                modifier = Modifier.padding(horizontal = 12.dp, vertical = 4.dp),")
L("                                fontSize = 16.sp,")
L("                                color = MaterialTheme.colorScheme.onPrimary,")
L("                                fontFamily = SblHebrew,")
L("                                fontWeight = FontWeight.SemiBold")
L("                            )")
L("                        }")
L("                    }")
L("                }")
L("                Row {")
L("                    IconButton(")
L("                        onClick = onRefreshClick,")
L("                        modifier = Modifier.clip(CircleShape).background(Color.White.copy(alpha = 0.15f))")
L("                    ) {")
L('                        Icon(Icons.Rounded.Refresh, contentDescription = "\u05e8\u05e2\u05e0\u05df", tint = MaterialTheme.colorScheme.onPrimary)')
L("                    }")
L("                    Spacer(modifier = Modifier.width(8.dp))")
L("                    IconButton(")
L("                        onClick = onSettingsClick,")
L("                        modifier = Modifier.clip(CircleShape).background(Color.White.copy(alpha = 0.15f))")
L("                    ) {")
L('                        Icon(Icons.Rounded.Settings, contentDescription = "\u05d4\u05d2\u05d3\u05e8\u05d5\u05ea", tint = MaterialTheme.colorScheme.onPrimary)')
L("                    }")
L("                }")
L("            }")
L("        }")
L("    }")
L("}")
L()
L("@Composable")
L("private fun DailyProgressCard(todayStatus: List<Pair<String, Boolean>>) {")
L("    val done = todayStatus.count { it.second }")
L("    val total = todayStatus.size")
L("    val progress = if (total > 0) done.toFloat() / total else 0f")
L("    val allDone = done == total && total > 0")
L()
L("    Card(")
L("        modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp).offset(y = (-16).dp),")
L("        shape = RoundedCornerShape(24.dp),")
L("        colors = CardDefaults.cardColors(containerColor = if (allDone) MaterialTheme.colorScheme.secondaryContainer else MaterialTheme.colorScheme.surface),")
L("        elevation = CardDefaults.cardElevation(defaultElevation = 6.dp)")
L("    ) {")
L("        Row(modifier = Modifier.fillMaxWidth().padding(20.dp), verticalAlignment = Alignment.CenterVertically) {")
L("            Box(modifier = Modifier.size(72.dp), contentAlignment = Alignment.Center) {")
L("                val ringColor = if (allDone) MaterialTheme.colorScheme.secondary else MaterialTheme.colorScheme.primary")
L("                val trackColor = MaterialTheme.colorScheme.surfaceVariant")
L("                Canvas(modifier = Modifier.fillMaxSize()) {")
L("                    val stroke = 8.dp.toPx()")
L("                    drawArc(color = trackColor, startAngle = -90f, sweepAngle = 360f, useCenter = false, style = Stroke(width = stroke))")
L("                    if (progress > 0f) {")
L("                        drawArc(color = ringColor, startAngle = -90f, sweepAngle = 360f * progress, useCenter = false, style = Stroke(width = stroke, cap = StrokeCap.Round))")
L("                    }")
L("                }")
L('                Text(text = "$done/$total", fontSize = 16.sp, fontWeight = FontWeight.ExtraBold, color = ringColor)')
L("            }")
L("            Spacer(Modifier.width(20.dp))")
L("            Column(modifier = Modifier.weight(1f)) {")
L("                Text(")
L('                    text = if (allDone) "\u05db\u05dc \u05d4\u05db\u05d1\u05d5\u05d3! \u05e1\u05d9\u05d9\u05de\u05ea \u05d4\u05db\u05dc" else "\u05d4\u05d4\u05ea\u05e7\u05d3\u05de\u05d5\u05ea \u05e9\u05dc\u05da \u05dc\u05d4\u05d9\u05d5\u05dd",')
L("                    fontSize = 18.sp,")
L("                    fontWeight = FontWeight.Bold,")
L("                    color = if (allDone) MaterialTheme.colorScheme.onSecondaryContainer else MaterialTheme.colorScheme.onSurface")
L("                )")
L("                Spacer(Modifier.height(4.dp))")
L("                Text(")
L('                    text = if (allDone) "\u05e2\u05d1\u05e8\u05ea \u05e2\u05dc \u05db\u05dc $total \u05d4\u05dc\u05d9\u05de\u05d5\u05d3\u05d9\u05dd \u05d4\u05d9\u05d5\u05dd!" else "\u05e0\u05e9\u05d0\u05e8\u05d5 \u05dc\u05da \u05e2\u05d5\u05d3 ${total-done} \u05dc\u05d9\u05de\u05d5\u05d3\u05d9\u05dd",')
L("                    fontSize = 14.sp,")
L("                    color = MaterialTheme.colorScheme.onSurfaceVariant")
L("                )")
L("            }")
L("        }")
L("    }")
L("}")
L()
L("@Composable")
L("private fun StudyCard(study: Study, modifier: Modifier = Modifier, onClick: () -> Unit) {")
L("    val available = study.available == true")
L("    val accentColor = when (study.accent) {")
L('        "blue" -> Color(0xFF0284C7)')
L('        "emerald" -> Color(0xFF059669)')
L('        "violet" -> Color(0xFF7C3AED)')
L('        "amber" -> Color(0xFFD97706)')
L("        else -> MaterialTheme.colorScheme.primary")
L("    }")
L("    val cardAccent = if (available) accentColor else MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.3f)")
L()
L("    Card(")
L("        modifier = modifier.fillMaxWidth().clip(RoundedCornerShape(20.dp)).clickable(enabled = available, onClick = onClick),")
L("        shape = RoundedCornerShape(20.dp),")
L("        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),")
L("        elevation = CardDefaults.cardElevation(defaultElevation = if (available) 3.dp else 1.dp)")
L("    ) {")
L("        Row(modifier = Modifier.fillMaxWidth().height(IntrinsicSize.Min)) {")
L("            Box(modifier = Modifier.width(6.dp).fillMaxHeight().background(cardAccent))")
L("            Column(modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 16.dp)) {")
L("                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.Top) {")
L("                    Column(modifier = Modifier.weight(1f)) {")
L("                        Text(")
L('                            text = study.title ?: "",')
L("                            fontSize = 18.sp,")
L("                            fontWeight = FontWeight.Bold,")
L("                            color = if (available) MaterialTheme.colorScheme.onSurface else MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.6f),")
L("                            fontFamily = SblHebrew")
L("                        )")
L("                        if (!study.subtitle.isNullOrEmpty()) {")
L("                            Spacer(Modifier.height(2.dp))")
L("                            Text(text = study.subtitle, fontSize = 14.sp, color = MaterialTheme.colorScheme.onSurfaceVariant, fontFamily = SblHebrew)")
L("                        }")
L("                    }")
L("                    if (available && !study.label.isNullOrEmpty()) {")
L("                        Spacer(Modifier.width(12.dp))")
L("                        Surface(shape = RoundedCornerShape(8.dp), color = cardAccent.copy(alpha = 0.1f)) {")
L("                            Text(")
L("                                text = study.label,")
L("                                modifier = Modifier.padding(horizontal = 10.dp, vertical = 4.dp),")
L("                                fontSize = 13.sp,")
L("                                fontWeight = FontWeight.Bold,")
L("                                color = cardAccent,")
L("                                textAlign = TextAlign.End,")
L("                                fontFamily = SblHebrew,")
L("                                style = LocalTextStyle.current.copy(textDirection = TextDirection.Rtl)")
L("                            )")
L("                        }")
L("                    }")
L("                }")
L("                if (available && !study.preview.isNullOrEmpty()) {")
L("                    Spacer(Modifier.height(10.dp))")
L("                    Text(")
L("                        text = study.preview,")
L("                        fontSize = 14.sp,")
L("                        lineHeight = 22.sp,")
L("                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.75f),")
L("                        maxLines = 2,")
L("                        overflow = TextOverflow.Ellipsis,")
L("                        fontFamily = SblHebrew,")
L("                        style = LocalTextStyle.current.copy(textDirection = TextDirection.Rtl)")
L("                    )")
L("                }")
L("                if (!available) {")
L("                    Spacer(Modifier.height(6.dp))")
L('                    Text(text = "\u05dc\u05d0 \u05e0\u05de\u05e6\u05d0\u05d5 \u05e0\u05ea\u05d5\u05e0\u05d9\u05dd \u05dc\u05d4\u05d9\u05d5\u05dd", fontSize = 13.sp, color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.6f))')
L("                }")
L("            }")
L("        }")
L("    }")
L("}")
L()
L("@Composable")
L("private fun QuickAccessRow(onTefilaClick: () -> Unit, onOmerClick: () -> Unit, onToolsClick: () -> Unit) {")
L("    Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp), horizontalArrangement = Arrangement.spacedBy(10.dp)) {")
L("        QuickAccessButton(")
L('            label = "\u05ea\u05e4\u05d9\u05dc\u05d4",')
L("            icon = Icons.AutoMirrored.Filled.MenuBook,")
L("            color = Color(0xFF0284C7),")
L("            onClick = onTefilaClick,")
L("            modifier = Modifier.weight(1f)")
L("        )")
L("        QuickAccessButton(")
L('            label = "\u05e2\u05d5\u05de\u05e8",')
L("            icon = Icons.Default.DateRange,")
L("            color = Color(0xFF7C3AED),")
L("            onClick = onOmerClick,")
L("            modifier = Modifier.weight(1f)")
L("        )")
L("        QuickAccessButton(")
L('            label = "\u05db\u05dc\u05d9\u05dd",')
L("            icon = Icons.Default.Build,")
L("            color = Color(0xFF059669),")
L("            onClick = onToolsClick,")
L("            modifier = Modifier.weight(1f)")
L("        )")
L("    }")
L("}")
L()
L("@Composable")
L("private fun QuickAccessButton(label: String, icon: ImageVector, color: Color, onClick: () -> Unit, modifier: Modifier = Modifier) {")
L("    Card(")
L("        modifier = modifier.clickable(onClick = onClick),")
L("        shape = RoundedCornerShape(14.dp),")
L("        colors = CardDefaults.cardColors(containerColor = color.copy(alpha = 0.08f)),")
L("        elevation = CardDefaults.cardElevation(1.dp)")
L("    ) {")
L("        Column(modifier = Modifier.fillMaxWidth().padding(vertical = 14.dp), horizontalAlignment = Alignment.CenterHorizontally) {")
L("            Icon(icon, contentDescription = null, tint = color, modifier = Modifier.size(26.dp))")
L("            Spacer(Modifier.height(6.dp))")
L("            Text(text = label, fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = color, fontFamily = SblHebrew)")
L("        }")
L("    }")
L("}")
L()
L("@Composable")
L("private fun ErrorState(message: String, onRetry: () -> Unit, modifier: Modifier = Modifier) {")
L("    Column(modifier = modifier.padding(32.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(16.dp)) {")
L('        Text("\u05e9\u05d2\u05d9\u05d0\u05d4 \u05d1\u05d8\u05e2\u05d9\u05e0\u05d4", fontSize = 20.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onBackground)')
L("        Text(message, fontSize = 15.sp, color = MaterialTheme.colorScheme.onSurfaceVariant, textAlign = TextAlign.Center)")
L("        Button(onClick = onRetry, colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary), shape = RoundedCornerShape(12.dp)) {")
L('            Text("\u05e0\u05e1\u05d4 \u05e9\u05d5\u05d1", fontWeight = FontWeight.Bold)')
L("        }")
L("    }")
L("}")

with open(target, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"OK: wrote {len(lines)} lines to HomeScreen.kt")
